cfg_name: 'default'

# dataset
raw_base_dir: '/media/ljf/Data/kitti/kitti_raw'
kitti_odom_dir: '/media/ljf/Data/kitti/kitti_odometry/data_odometry_color/dataset'
prepared_base_dir: '/home/ljf/Dataset/kitti_release'
gt_2012_dir: '/media/ljf/Work/DATASET/kitti-flow/kitti2012/training'
gt_2015_dir: '/media/ljf/Work/DATASET/kitti-flow/kitti2015/data_scene_flow/training'
static_frames_txt: '/home/ljf/Documents/Unsupervised_geometry/data/eigen/static_frames.txt'
test_scenes_txt: '/home/ljf/Documents/Unsupervised_geometry/data/eigen/test_scenes.txt'
sequences: ['09']
dataset: 'kitti_depth'
num_scales: 3
num_input_frames: 3

# training
num_iterations: 200000

# loss hyperparameters
w_flow_pixel: 1.0 #0.15
w_flow_ssim: 0.85 # w_pixel = 1 - w_ssim
w_flow_smooth: 10.0 #10.0
w_flow_consis: 0.01

w_depth_pixel: 1.0 #0.15
w_depth_ssim: 0.85
w_depth_smooth: 0.1 # 10.0
w_depth_consis: 0.1

w_depth_flow_consis: 0.01
w_epipolar: 0.01
w_triangle: 0.001
w_pnp: 0.1
w_8point: 0.1

# flow_consist_alpha: 3.0
# flow_consist_beta: 0.05
flow_consist_alpha: 0.01
flow_consist_beta: 0.5

ransac_iters: 100
ransac_points: 6000

geometric_ratio: 0.3
geometric_num: 6000

pose_beta: 1

# basic info
img_hw: [256, 832]
use_svd_gpu: False